### ISSUE TITLE
JumpPads sound

### ISSUE THREAD

**Issue by PanikFaser** [GiantTreeLP/GroundMCPlugin#38]
Play this Sound on moving on JumpPads: ENDERDRAGON_WINGS

**Comment by GiantTreeLP** [comment]
Das heißt ENTITY_ENDERDRAGON_FLAP.

Schau dir die PR mal an.

Gepackte Beta: [groundmc-plugin-1.4.1-bnull.jar.zip](https://github.com/GiantTreeLP/GroundMCPlugin/files/1423082/groundmc-plugin-1.4.1-bnull.jar.zip)

**Comment by PanikFaser** [comment]
Der Sound soll beim abheben abgespielt werden

**Comment by GiantTreeLP** [comment]
Tut er ja.
