### ISSUE TITLE
Scoreboard

### ISSUE THREAD

**Issue by PanikFaser** [GiantTreeLP/GroundMCPlugin#43]
Ein Scoreboard, in dem ganz oben (ohne Zahl) der Spieler Name steht. Darunter dann in "GOLD"Spielzeit (Newline) "WEIß" XXh, XXmin  (Newline) "GELB"Coins (Newline) "WEIß" Coming Soon (Newline) "DUNKEL_TÜRKIS"Event (Newline) "HELL_GRÜN"Ja / "HELL_ROT"Nein (einstellbar in einer Datei z.B. scoreboard.yml)

Aussehen:

          <name> (z.B. "HELL_GRAU"PanikFaser)
     "GOLD"Spielzeit
     "WEIß"XXh, XXmin  (ne Art Zähler oder so einbauen)
     "GELB"Coins
     "WEIß"Coming Soon
     "DUNKEL_TÜRKIS"Event
     "HELL_GRÜN"Ja oder "HELL_ROT"Nein

**Comment by GiantTreeLP** [comment]
Ähm bitte die "&" Dinger als farbe, ich hab keine ahnung was die sein sollen

**Comment by GiantTreeLP** [comment]
Die Onlinezeit wird auf dem Server in Ticks (50ms) gespeichert, damit wäre eigentlich alles gegeben.

Die Umsetzung wird allerdings noch dauern, du kennst mich ja 😄

**Comment by PanikFaser** [comment]
Ok... das mit farbigem Namen lassen wir... musste auf CloudNet Permission system umstellen... nimm für den Namen einfach "HELL_GRAU"

**Comment by GiantTreeLP** [comment]
Neues Design:

```
     <GRAU>SpielerName
<GOLD>Spielzeit
<WEIß>XXh:XXm
<GELB>Coins
<WEIß>XXX
<DUNKEL_AQUAMARIN>Event
<HELL_GRÜN>JA! oder <HELL_ROT>Nein
<WEIẞ>...events...
```

**Comment by GiantTreeLP** [comment]
Events mit `/gl event add "beginn" "ende" "titel"` sind jetzt implementiert.  
Inklusive Rückmeldung an den User.
